version: '3'
services:
  certificate_authority:
     build: ./CertificateAuthority
  mosquitto:
    image: eclipse-mosquitto
    volumes:
     - ./config/:/mosquitto/config/:rw
    ports:
     - 1883:1883
     - 9001:9001
  broker:
    build: ./Broker
    depends_on:
      - certificate_authority
  vehicule1:
    build: ./Vehicules
    depends_on:
      - certificate_authority
  vehicule2:
    build: ./Vehicules
    depends_on:
      - certificate_authority
