version: '3'
services:
  ca:
     build: ./CertificateAuthority
  mosquitto:
    image: eclipse-mosquitto
    volumes:
     - ./config/:/mosquitto/config/:rw
    ports:
     - 1883:1883
     - 9001:9001
  broker:
    build: ./Broker
    depends_on:
      - mosquitto
      - ca
  vehicule1:
    build: ./Vehicules
    depends_on:
      - broker
      - ca
