version: '3'
services:
  certificate_authority:
     build: ./CertificateAuthority
  mosquitto:
    image: eclipse-mosquitto
    volumes:
     - ./config/:/mosquitto/config/:rw
    ports:
     - 1883:1883
     - 9001:9001
  broker:
    build: ./Broker
    depends_on:
      - mosquitto
      - certificate_authority
  vehicule1:
    build: ./Vehicules
    environment: 
      - MAX_MESSAGES=50
      - SLOW_START=20
      - SLOW_STOP=40
      - BROKER_ADDR="mosquitto"
      - BROKER_PORT=1883
    depends_on:
      - certificate_authority
  vehicule2:
    build: ./Vehicules
    environment: 
      - MAX_MESSAGES=50
      - SLOW_START=20
      - SLOW_STOP=40
      - BROKER_ADDR="mosquitto"
      - BROKER_PORT=1883
    depends_on:
      - certificate_authority
